#!/bin/bash

debug()
{
	if [[ "$minus" == *"b"* ]]
	then
		echo -e DEBUG: "$@"  >&2
	fi
}

usernameDefault="$USER"
keyFile=""
usernameSpec=""

declare -g -A config

####################### MKDIRs #######################################
mkdir -p ~/m
mkdir -p ~/.movingssh
mkdir -p ~/.movingssh/address/
mkdir -p ~/.movingssh/tunel/
mkdir -p ~/.movingssh/configDevice/

####################### PARSE ARG #######################################
for var in "$@"
do
	if [[ "$name" == "" ]]
	then
		if [[ "$var" == -* ]]
		then
			minus="$minus$var"
		else
			name="$var"
		fi
	else
		parametrs="$parametrs $var"
	fi
done

name="$name"
while [[ "${name:0:1}" == '_' ]]
do
	name="${name:1}"
done

####################### HELP #######################################
if [[ "$minus" == *"h"* ]]
then
	cat <<EOF
Auomatic ssh conect to device without private addrees by local ip starage at server or ssh tunel
Usage:
	movingssh [-parametrs] [user@]device [ssh command parametrs]

Parametrs:
	-h	print this help
	-b	print debuging messages
	-p	print address and port to connect
	-d	download new pozition just after run
	-D	do not download new pozition
	-x	do not run parralel
	-l	force use local conection
	-r	force use remote conection
	-m	sshfs mount
	-M	sshfs mount without links eval
	-u	umount
	-U	force umount
	-t	Make tunel
	-T	Delete tunel route
	-v	Connect x11vnc session view only
	-V	Connect x11vnc session with control
	-c	Connect vnc session
	-n	Do not tunel X server by -Y
	-N	Do not tunel X server by -Y, tunel it only by -X
	-g 	Only print addres for use
	-s	use moSh
	-2	use second tunel (port number plus one)
	-A	do not use key agent
	-a	use key agent
	-e	tunel ssh agEnt
EOF
	exit 0
fi

####################### PARSE ARG #######################################
xtunelCMD="-Y"
[[ "$minus" == *"N"* ]] && xtunelCMD="-X"
[[ "$minus" == *"n"* ]] && xtunelCMD=""
[[ "$minus" == *"v"* ]] && xtunelCMD=""
[[ "$minus" == *"V"* ]] && xtunelCMD=""
[[ "$minus" == *"c"* ]] && xtunelCMD=""

if [[ "$name" == "" ]]
then
	echo NO ARGUMENTS >&2
	exit 0
fi
if [[ "$name" == *"@"* ]]
then
	usernameSpec="$(echo "$name" | cut -d'@' -f1)"
	name="$(echo "$name" | cut -d'@' -f2)"
fi
timeout=2
sleepTime=10

addressFile=~/.movingssh/address/$name
tunelFile=~/.movingssh/tunel/$name
configFile=~/.movingssh/configDevice/$name
mountpoint=~/m/$name
servermountpoint=/
[[ "$MS_MOUNTPOINT" != "" ]] && mountpoint="$MS_MOUNTPOINT"
[[ "$MS_SERVERMOUNTPOINT" != "" ]] && servermountpoint="$MS_SERVERMOUNTPOINT"

pipeFile=$(mktemp -u)
mkfifo $pipeFile
exec 3<>$pipeFile
rm $pipeFile

timeoutCMD="-o ConnectTimeout=$timeout"
envCMD="-o SendEnv=LD_SSHTYPE -o SendEnv=LC_SSHTYPE"
keyCMD="-o HostKeyAlias=$name"
useAgent=false

[[ "$downloadServer" == "" ]] && downloadServer="jirikalvoda@kam.mff.cuni.cz"

####################### IMPUT CONFIGs #######################################
[[ -f ~/.movingssh/config ]] && 	. ~/.movingssh/config
[ -f "$configFile" ] && . $configFile

	if [ -d ~/.movingssh/groups ]
	then
		for i in  ~/.movingssh/groups/*
		do
			. $i
		done
	fi

####################### PROCES ARGS #######################################

if [[ $usernameSpec == "" ]]
then
	username="$usernameDefault"
else
	username="$usernameSpec"
fi
keyFileCMD=""
[[ "$keyFile" != "" ]] && keyFileCMD="-o IdentityFile=$keyFile"


####################### AGENT #######################################



[[ "$minus" == *"a"* ]] && useAgent=true
[[ "$minus" == *"A"* ]] && useAgent=false

[[ "$minus" == *"e"* ]] && useAgent=false
if $useAgent
then
	eval $(ssh-agent -s -t 30 | head -n2)
	if [[ "$keyFile" != "" ]]
	then
		ssh-add "$keyFile"
	fi
fi

if [[ "$minus" == *"e"* ]]
then
	eval $(ssh-agent -s)
	agentTumelCMD="-A"
	ssh-add ~/.ssh/id_ed25519
	ssh-add ~/.ssh/id_rsa
	if [[ "$keyFile" != "" ]]
	then
		ssh-add "$keyFile"
	fi
fi

####################### FUNCTIONS #######################################

kilrek()
{
	pgrep -P $1 | while read p;
	do
		kilrek $p;
		#echo $p;
		kill $p;
	done
}

killallmy()
{
	pgrep -P $$ |  while read p;
	do
		name=$(ps -p $p -o comm=)
		if [[ " $* " == *"$name"* ]]
		then
			debug KILL $p $name
			kill $p
		fi
	done
}

parseAddresFile()
{
	debug PARSE CONFIG
	#shopt -s extglob
	if [ -f "$addressFile" ]
	then
		while IFS='= ' read -r lhs rhs
		do
		    if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
			rhs="${rhs%%\#*}"    # Del in line right comments
			rhs="${rhs%%*( )}"   # Del trailing spaces
			rhs="${rhs%\"*}"     # Del opening string quotes 
			rhs="${rhs#\"*}"     # Del closing string quotes 
			config[$lhs]="$rhs"
		    fi
		done < $addressFile
	fi
	if [[ "$1" != "notunel" ]] && [ -f $tunelFile ] 
	then
		while IFS='= ' read -r lhs rhs
		do
			if [[ ! $lhs =~ ^\ *# && -n $lhs ]]; then
			rhs="${rhs%%\#*}"    # Del in line right comments
			rhs="${rhs%%*( )}"   # Del trailing spaces
			rhs="${rhs%\"*}"     # Del opening string quotes 
			rhs="${rhs#\"*}"     # Del closing string quotes 
			config[$lhs]="$rhs"
			fi
		done < $tunelFile
	fi
}

printAddres()
{
	if [[ "$minus" == *"p"* ]]
	then
		(
		echo A: ${config[ipA]} ${config[portA]}  >&2
		echo B: ${config[ipB]} ${config[portB]}  >&2
		) | column -t -N \ ,ip,port
	fi
}

download()
{
	[[ "$noDownload" != "" ]] && return
	if [[ "$minus" != *"d"* ]] && [[ "${config[noDownload]}" != "" ]]
	then
		return 0
	fi
	if [[ "$minus" == *"D"* ]]
	then
		return 0
	fi
	debug DOWNLOAD
	#echo -en "\e[91mDOWNLOAD\e[0m\015" 1>&2
	newConfigFile=$(mktemp)
	ssh $downloadServer  $timeoutCMD "cat /home/jirikalvoda/.movingssh/address/$name" > $newConfigFile 2>/dev/null
	#echo -en "\e[92mDOW DONE\e[0m\015" 1>&2
	if [[ $? = 0 ]]
	then
		debug DOWNLOAD OK
		diff $addressFile $newConfigFile -q >/dev/null
		if [[ $? != 0 ]]
		then
			debug DIFF CONFIG
			cat $newConfigFile > $addressFile
			parseAddresFile
			printAddres
			rm $newConfigFile
			return 1
		fi
		rm $newConfigFile
		return 0
	else
		debug NO NET
		rm $newConfigFile
		return 0
	fi
}

tryLocal()
{
	debug TRY LOCAL
	#echo -en "\e[91mTRY LOC \e[0m\015" 1>&2
	#declare -p config
	if [[ "${config[portA]}" == "" ]]
	then
		config[portA]=22
	fi
	if [[ "${config[ipA]}" == "" ]]
	then
		ret=
		debug LOCAL NO IPA
	else
		ret=$(LD_SSHTYPE=try LC_SSHTYPE=try ssh $envCMD $username@${config[ipA]} -p${config[portA]} $keyFileCMD $keyCMD $timeoutCMD echo OK 2>/dev/null)
	fi
	#echo -en "\e[92mTRY DONE\e[0m\015" 1>&2
	if [ "$ret" = "OK" ]
	then
		debug LOCAL OK
		killallmy ssh
		echo YES >&3
		return 1
	fi
	debug LOCAL NO
	echo NO >&3
	return 0
}
tryLocalDownload()
{
	tryLocal
	if [[ $? == 1 ]]
	then
		return;
	fi
	if [[ "$minus" == *"d"* ]]
	then
		return;
	fi
	download
	if [[ $? == 0 ]]
	then
		return
	fi
	tryLocal
}

x11vnc()
{
	vncTunelPort=$(( 40000 + $RANDOM % 10000 ))
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >&2
	echo "XXX              PORT $vncTunelPort             XXX" >&2
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >&2
	sudoCmd=""
	passwdFile=$(mktemp)
	head -c100 /dev/random | shasum | head -c30 > $passwdFile
	[[ "$SUDO" != "" ]] && sudoCmd="sudo -u $SUDO" 
	[[ "$VNCDISPLAY" == "" ]] && VNCDISPLAY=":0"
	vncviewerOpt=""
	[[ "$minus" == *"V"* ]] || vncviewerOpt="-ViewOnly"
	(sleep 1; while true; do VNC_PASSWORD="$(cat $passwdFile)" vncviewer $vncviewerOpt localhost::$vncTunelPort ; done ) &
	cat $passwdFile | ssh -t $envCMD $username@$1 -p$2 $keyFileCMD $keyCMD -L$vncTunelPort:localhost:$vncTunelPort $sudoCmd bash -c "\"cat | x11vnc -localhost -display $VNCDISPLAY -autoport  $vncTunelPort -forever -passwdfile /dev/stdin\""
	r=$(ssh -t $envCMD $username@$1 -p$2 $keyFileCMD $keyCMD $sudoCmd bash -c" \"pkill -f autoport\\\" $vncTunelPort\\\" ; echo -n OK\$?\"")
	[[ "$r" != "OK0" ]] && echo -e "\e[31;1m### CLEAN FAILD $r ####\e[0m" >&2
	rm $passwdFile
	killallmy movingssh
}

vncserver()
{
	vncDisplay=$(( $RANDOM % 900 + 100 ))
	vncTunelPort=$(( 5900 + $vncDisplay ))
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >&2
	echo "XXX              PORT $vncTunelPort             XXX" >&2
	echo "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX" >&2
	sudoCmd=""
	passwdFile=$(mktemp)
	head -c100 /dev/random | shasum | head -c30 > $passwdFile
	[[ "$SUDO" != "" ]] && sudoCmd="sudo -u $SUDO" 
	(sleep 0.5; while true; do VNC_PASSWORD="$(cat $passwdFile)" vncviewer  localhost::$vncTunelPort ; done ) &
	( cat $passwdFile; echo; cat $passwdFile; echo ;echo n; cat ) | ssh -t $envCMD $username@$1 -p$2 $keyFileCMD $keyCMD -L$vncTunelPort:localhost:$vncTunelPort $sudoCmd bash -c " \"vncpasswd ; vncserver :$vncDisplay\""
	r=$(ssh -t $envCMD $username@$1 -p$2 $keyFileCMD $keyCMD $sudoCmd bash -c" \"pkill -f Xvnc\\\" :$vncDisplay -auth\\\" ; echo -n OK\$?\"")
	[[ "$r" != "OK0" ]] && echo -e "\e[31;1m### CLEAN FAILD $r ####\e[0m" >&2
	rm $passwdFile
	killallmy movingssh
}

printGetAddres()
{
	case $(echo $parametrs) in
		P)
			echo $username@$1 -P$2
			;;
		p)
			echo $username@$1 -P$2
			;;
		"rsync")
			echo $username@$1:
			echo -e=\'ssh $envCMD -p$2  $keyFileCMD $keyCMD\'
			;;
		"rsyncnoesc")
			echo $username@$1:
			echo -e=ssh $envCMD -p$2  $keyFileCMD $keyCMD
			;;
		*)
			echo $username $1 $2
			;;
	esac
	sleep $timeout
}

conect()
{
	LC_SSHTYPE=$LD_SSHTYPE
	export LC_SSHTYPE
	if [[ "$minus" == *"g"* ]]
	then
		printGetAddres "$@"
		return 255
	fi
	if [[ "$minus" == *"v"* ]] || [[ "$minus" == *"V"* ]]
	then
		x11vnc $@
		return $?
	elif [[ "$minus" == *"c"* ]]
	then
		vncserver $@
		return $?
	elif [[ "$minus" == *"s"* ]]
	then
		mosh  $username@$1 --ssh="ssh $envCMD -p$2 $xtunelCMD  $keyFileCMD $keyCMD $parametrs"
		return $?
	elif [[ "$minus" == *"m"* ]] || [[ "$minus" == *"M"* ]]
	then
		if [[ -d "$mountpoint" || -f "$mountpoint" ]]
		then
			rmdir $mountpoint
		fi
		if [[ -d "$mountpoint" || -f "$mountpoint" ]]
		then
			echo DIRECTORY $mountpoint EXISTS >&2
			echo Unmout it first please >&2
			exit 100
		fi
		mkdir $mountpoint
		[[ "$minus" == *"m"* ]] && sshfs -o follow_symlinks -C $username@$1:$servermountpoint -p $2 $keyFileCMD $keyCMD $mountpoint
		[[ "$minus" == *"M"* ]] && sshfs -C $username@$1:$servermountpoint -p $2 $keyFileCMD $keyCMD $mountpoint
	else
		debug RUN: ssh $envCMD $username@$1 -p$2 $xtunelCMD $keyFileCMD $keyCMD $parametrs $agentTumelCMD
		ssh $envCMD $username@$1 -p$2 $xtunelCMD  $keyFileCMD $keyCMD $parametrs $agentTumelCMD
		return $?
	fi
}

remote()
{
	debug REMOTE
	echo -en "\e[91mREMOTE  \e[0m\015" 2>/dev/null 1>&2
	if [[ "${config[portB]}" == "" ]]
	then
		config[portB]=22
	fi
	if [[ "${config[ipB]}" == "" ]]
	then
		return 255
	else
		if [[ "$minus" == *"2"* ]]
		then
			LD_SSHTYPE=second conect ${config[ipB]} $(( ${config[portB]} + 1))
		else
			LD_SSHTYPE=remote conect ${config[ipB]} ${config[portB]}
		fi
		return $?
	fi
}
local()
{
	debug LOCAL
	echo -en "\e[96mLOCAL   \e[0m\015" 1>&2
	if [[ "${config[portA]}" == "" ]]
	then
		config[portA]=22
	fi
	if [[ "${config[ipA]}" == "" ]]
	then
		return 255
	else
		LD_SSHTYPE=local conect ${config[ipA]} ${config[portA]}
		return $?
	fi
}

if [[ "$minus" == *"T"* ]]
then
	rm $tunelFile
fi

parseAddresFile
printAddres
if [[ "$minus" == *"u"* || "$minus" == *"U"* ]]
then
	if [[ -d "$mountpoint"  ]]
	then
		if [[ "$minus" == *"U"* ]]
		then
			umount -l  $mountpoint
		else
			umount  $mountpoint
		fi
		if [ $? != 0 ]
		then
			echo UMOUNT FAILD >&2
			rmdir $mountpoint
			exit 100
		fi
		rmdir $mountpoint
	else
		echo DIRECTORY $mountpoint NOT EXISTS >&2
		exit 100
	fi
	exit 0
fi
if [[ "$minus" == *"d"* ]]
then
	download
fi
if [[ "$minus" == *"t"* ]]
then
	parseAddresFile notunel
	tunelPort=$(( 40000 + $RANDOM % 10000 ))
	echo -e "ipB=localhost\nportB=$tunelPort" > $tunelFile
	echo -e "\e[4;1;31mSSH TUNEL TO $name ON PORT $tunelPort \e[0m" >&2
	ssh -p 443 jirikalvoda@sneaky.kam.mff.cuni.cz -L $tunelPort:${config[ipB]}:${config[portB]} "read"
	echo END >&2
	rm $tunelFile
	exit 0
fi
if [[ "$minus" == *"l"* ]]
then
	local
elif [[ "$minus" == *"r"* ]]
then
	remote
elif [[ "$minus" == *"x"* ]] || [[ "$minus" == *"v"* ]] || [[ "$minus" == *"V"* ]] || [[ "$minus" == *"c"* ]] || [[ "$minus" == *"m"* ]] || [[ "$minus" == *"M"* ]]
then
	tryLocalDownload
	echo NO >&3
	if [ "$(head -n1 <&3)" == "YES" ]
	then
		echo LOCAL >&2
		local
	else
		echo '********REMOTE**********' >&2
		remote
	fi
else
	tryLocalDownload &
	remote
	r=$?
	debug return $r
	if [ $r = 255 ] || [ $r = 143 ]
	then
		debug START READ PIPE
		from_pipe="$(head -n1 <&3)"
		debug FROM PIPE "$from_pipe"
		if [ "$from_pipe" == "YES" ]
		then
			debug END HEAD
			parseAddresFile
			local
		fi
	fi
fi


exec 3>&-
pgrep -P $BASHPID | while read p;
do
	kilrek $p;
done
