#!/bin/bash
echo localhost:3003 > ~/.secret/mqtt/rpi0-all.tunel
movingssh -dx rpi0 -L3001:localhost:3001 -L3002:localhost:22 -L3000:localhost:3000 -L3003:localhost:1883
rm ~/.secret/mqtt/rpi0-all.tunel
