#!/bin/bash
if [[ "$1" == "-e" ]]
then
	shift
fi

am startservice \
	-n com.termux/com.termux.app.RunCommandService \
	-a com.termux.RUN_COMMAND \
	--es com.termux.RUN_COMMAND_PATH '/data/data/com.termux/files/home/arch' \
	--esa com.termux.RUN_COMMAND_ARGUMENTS "-u,$USER,-t,--$(printf ',%s' "$@")" \
	--es com.termux.RUN_COMMAND_WORKDIR '/data/data/com.termux/files/home' \
	--ez com.termux.RUN_COMMAND_BACKGROUND 'false' \
	--es com.termux.RUN_COMMAND_SESSION_ACTION '0'

# TODO Escape , -> \,
