# A sample configuration for dhcpcd.
# See dhcpcd.conf(5) for details.

# Allow users of this group to interact with dhcpcd via the control socket.
#controlgroup wheel

# Inform the DHCP server of our hostname for DDNS.
#hostname

# Use the hardware address of the interface for the Client ID.
#clientid
# or
# Use the same DUID + IAID as set in DHCPv6 for DHCPv4 ClientID as per RFC4361.
# Some non-RFC compliant DHCP servers do not reply with this set.
# In this case, comment out duid and enable clientid above.
duid

# Persist interface configuration when dhcpcd exits.
persistent

# # vendorclassid is set to blank to avoid sending the default of
# # dhcpcd-<version>:<os>:<machine>:<platform>
# vendorclassid

# A list of options to request from the DHCP server.
option domain_name_servers, domain_name, domain_search
option classless_static_routes
# Respect the network MTU. This is applied to DHCP routes.
option interface_mtu

# # Request a hostname from the network
# option host_name

# Most distributions have NTP support.
#option ntp_servers

# Rapid commit support.
# Safe to enable by default because it requires the equivalent option set
# on the server to actually work.
option rapid_commit

# A ServerID is required by RFC2131.
require dhcp_server_identifier

# Generate SLAAC address using the Hardware Address of the interface
#slaac hwaddr
# OR generate Stable Private IPv6 Addresses based from the DUID
slaac private
# Don't attempt to obtain an IPv4LL address if we failed to get one via DHCP.  See RFC 3927.
noipv4ll
noarp

nodelay




ssid MS-KAM-GUESTS
static ip_address=10.10.10.78/24
static ip6_address=2001:718:1e03:81a::4e/64
static routers=10.10.10.1
static domain_name_servers=195.113.17.177
static domain_name=kam.mff.cuni.cz
#static domain_search=
noipv6rs



ssid blatto-jk-5g
static ip_address=10.12.11.22/24
static ip6_address=2a01:b380:3000:181a::22/64
static routers=10.12.11.1
static domain_name_servers=10.12.11.1
static domain_name=jk.blatto.eu
static domain_search=jk.blatto.eu blatto.eu
noipv6rs
