#!/bin/bash
cd "$(dirname "$0")"

git remote -v
echo 

git remote | while read r
do
	git remote remove $r
done

git remote add ucw jirikalvoda@jabberwock.ucw.cz:GIT/userconfig
git remote add gitlab git@gitlab.com:JiriKalvoda/userconfig.git
git remote add github git@github.com:JiriKalvoda/userconfig.git

echo 
git remote -v
