#!/bin/bash
set -uo xtrace -o pipefail
. /etc/net/blatto.config

set -o xtrace

do_route_flush=\${1:-false}
adopt=$blatto_wg_adopt

ip link del wg-blatto || true
rm /run/wg-blatto/ -r || true

ip link add dev wg-blatto type wireguard
ip addr add $blatto_wg_ipv4/24 dev wg-blatto metric 1100
ip addr add $blatto_wg_ipv6/64 dev wg-blatto metric 1100
wg set wg-blatto listen-port $blatto_wg_port private-key /etc/wireguard/blatto/$blatto_device_id.key
wg set wg-blatto peer $(cat /etc/wireguard/blatto/blattes.pub) preshared-key /etc/wireguard/blatto/psk endpoint $blatto_public_ipv4:$blatto_wg_port allowed-ips 0.0.0.0/0,::0/0
ip link set mtu 1432 dev wg-blatto
ip link set wg-blatto up

for ups in $blatto_upstreams
do
	ups_id=blatto_upstream_${ups}_id
	ups_id=${!ups_id}
	ip link del wg-blatto2$ups || true
	ip link add wg-blatto2$ups type sit remote $blatto_wg_v4net.$ups_id local any mode any
	ip link set wg-blatto2$ups up
	ip route add $blatto_wg_v4net.0/24 dev wg-blatto table 12$ups_id metric 1100 src $blatto_wg_ipv4
	ip route add $blatto_wg_v6net::0/64 dev wg-blatto table 12$ups_id metric 1100 src $blatto_wg_ipv6
	ip route add default dev wg-blatto2$ups  table 12$ups_id metric 1100 src $blatto_wg_ipv4
	ip route add default dev wg-blatto2$ups  table 12$ups_id metric 1100 src $blatto_wg_ipv6
done

ip route add $blatto_wg_v4net.0/24 dev wg-blatto table 121 metric 1100 src $blatto_wg_ipv4
ip route add $blatto_wg_v6net::0/64 dev wg-blatto table 121 metric 1100 src $blatto_wg_ipv6
ip route add default dev wg-blatto table 121 metric 1100 src $blatto_wg_ipv4
ip route add default dev wg-blatto table 121 metric 1100 src $blatto_wg_ipv6

ip route add $blatto_wg_v4net.0/24 dev wg-blatto table 12 metric 1100 src $blatto_wg_ipv4
ip route add $blatto_wg_v6net::0/64 dev wg-blatto table 12 metric 1100 src $blatto_wg_ipv6
ip route add $blatto_wholev4 dev wg-blatto table 12 metric 1100 src $blatto_wg_ipv4
ip route add $blatto_wholev6 dev wg-blatto table 12 metric 1100 src $blatto_wg_ipv6

mkdir /run/wg-blatto/
echo $adopt > /run/wg-blatto/adopt

systemctl reload net-blatto-daemon

if $adopt
then
	ip addr add $blatto_ipv4/32 dev wg-blatto metric 1000
	ip addr add $blatto_ipv6/128 dev wg-blatto metric 1000

	ip route add $blatto_wholev4 dev wg-blatto table 12 metric 1000 src $blatto_ipv4
	ip route add $blatto_wholev6 dev wg-blatto table 12 metric 1000 src $blatto_ipv6

	ip route add default dev wg-blatto table 121 metric 1000 src $blatto_ipv4
	ip route add default dev wg-blatto table 121 metric 1000 src $blatto_ipv6

	for ups in $blatto_upstreams
	do
		ups_id=blatto_upstream_${ups}_id
		ups_id=${!ups_id}
		ip route add default dev wg-blatto2$ups  table 12$ups_id metric 1000 src $blatto_ipv4
		ip route add default dev wg-blatto2$ups  table 12$ups_id metric 1000 src $blatto_ipv6
	done
fi

# HACK
ip addr del $blatto_wg_ipv4/24 dev wg-blatto metric 1100
ip addr add $blatto_wg_ipv4/24 dev wg-blatto metric 1100
