#!/bin/sh

set -ueo pipefail

#interface=enp3s0f4u1u1
interface=sm

echo R | socat unix:/run/conntrack_hack -
ip link set $interface up
ip addres add 10.12.11.22/24 dev $interface
ip addres add 2a01:510:d504:7510::22/64 dev $interface
ip route add default via 10.12.11.1 dev $interface
ip route add default via 2a01:510:d504:7510::1 dev $interface
(echo domain jk.blatto.eu;  echo nameserver 10.12.11.1 ) | resolvconf -a $interface
