#!/bin/bash
set -euo xtrace -o pipefail

vlan_name=$1
id=$2
default_routing=${3:-blatto}

eval "$(ssh root@blatto.eu wg-get-metadata $vlan_name)"


mkdir -p /etc/wireguard/blatto
cd /etc/wireguard/blatto/
[ -f psk ] || (umask 0077 && wg genpsk > psk)
[ -f $id.key ] || wg genkey | (umask 0077 && tee $id.key) | wg pubkey > $id.pub

ssh root@blatto.eu cat /etc/wireguard/$vlan_name/blattes.pub > blattes.pub
cat psk | ssh root@blatto.eu "wg-register $vlan_name $id $(hostname) $(cat $id.pub)" < psk

#cat $id.pub | ssh root@blatto.eu "cat > /etc/wireguard/$vlan_name/$id.pub"
#cat psk | ssh root@blatto.eu "cat > /etc/wireguard/$vlan_name/$id.psk"


mkdir -p /etc/net

cat <<AMEN > /etc/net/wg-blatto
#!/bin/sh
set -o xtrace

ip link del wg-blatto || true
ip route flush table 12
ip -6 route flush table 12

ip link add dev wg-blatto type wireguard
ip addr add $v4net.$id/24 dev wg-blatto metric 100
ip addr add $v6net::$id/64 dev wg-blatto metric 100
wg set wg-blatto listen-port 12061 private-key /etc/wireguard/blatto/$id.key
wg set wg-blatto peer \$(cat /etc/wireguard/blatto/blattes.pub) preshared-key /etc/wireguard/blatto/psk endpoint $blattes_ipv4:$port allowed-ips 0.0.0.0/0,::0/0
ip link set mtu 1432 dev wg-blatto
ip link set wg-blatto up

ip route add throw 10.0.0.0/8 table 12
ip route add throw 192.168.0.0/16 table 12
ip route add throw 172.16.0.0/12 table 12
ip route add $v4net.0/24 dev wg-blatto table 12
ip rule add not to $blattes_ipv4 ipproto udp dport $port table 12
ip -6 route add throw fe80::/10 table 12
ip -6 route add throw fc00::/7 table 12
ip -6 route add $v6net::/64 dev wg-blatto table 12
ip -6 rule add table 12

/etc/net/wg-blatto-route $default_routing
AMEN

cat <<AMEN > /etc/net/wg-blatto-route
#!/bin/sh
set -o xtrace

blatto=del
default=del
adopt_blatto=del
adopt_default=del
adopt=del

if [ \$1 = no ]
then
	true
elif [ \$1 = blatto ]
then
	blatto=add
elif [ \$1 = all ]
then
	blatto=add
	default=add
elif [ \$1 = adopt_blatto ]
then
	blatto=add
	adopt_blatto=add
	adopt=add
elif [ \$1 = adopt_all ]
then
	blatto=add
	default=add
	adopt_blatto=add
	adopt_default=add
	adopt=add
else
	echo usage: \$0 no/blatto/all/adopt_blatto/adopt_all
	exit 1
fi


ip route \$blatto $ipv4_prefix.0.0/16 via $v4net.1 dev wg-blatto table 12 metric 100
ip route \$blatto ${ipv6_prefix}00::0/56 via $v6net::1 dev wg-blatto table 12 metric 100
ip route \$default default via $v4net.1 dev wg-blatto table 12 metric 100
ip route \$default default via $v6net::1 dev wg-blatto table 12 metric 100

ip addr \$adopt $adopt_v4net.$id/32 dev wg-blatto metric 1
ip addr \$adopt $adopt_v6net::$id/128 dev wg-blatto metric 1
ip route \$adopt_blatto $ipv4_prefix.0.0/16 dev wg-blatto table 12 metric 1 src $adopt_v4net.$id
ip route \$adopt_blatto ${ipv6_prefix}00::0/56 dev wg-blatto table 12 metric 1 src $adopt_v6net::$id
ip route \$adopt_default default dev wg-blatto table 12 metric 1 src $adopt_v4net.$id
ip route \$adopt_default default dev wg-blatto table 12 metric 1 src $adopt_v6net::$id

if [ \$adopt = add ]
then
	ip addr del $v4net.$id/24 dev wg-blatto metric 100
	ip addr add $v4net.$id/24 dev wg-blatto metric 100
fi
AMEN

chmod +x /etc/net/wg-blatto{,-route}
