#!/bin/bash
set -euo xtrace -o pipefail

vlan_name=$1
id=$2
adopt=false

[ "${3:-no}" == adopt ] && adopt=true

eval "$(ssh root@blatto.eu wg-get-metadata $vlan_name)"


mkdir -p /etc/wireguard/blatto
cd /etc/wireguard/blatto/
[ -f psk ] || (umask 0077 && wg genpsk > psk)
[ -f $id.key ] || wg genkey | (umask 0077 && tee $id.key) | wg pubkey > $id.pub

ssh root@blatto.eu cat /etc/wireguard/$vlan_name/blattes.pub > blattes.pub
cat psk | ssh root@blatto.eu "wg-register $vlan_name $id $(hostname) $(cat $id.pub)" < psk

#cat $id.pub | ssh root@blatto.eu "cat > /etc/wireguard/$vlan_name/$id.pub"
#cat psk | ssh root@blatto.eu "cat > /etc/wireguard/$vlan_name/$id.psk"


mkdir -p /etc/net

(
cat <<AMEN
#!/bin/sh
set -o xtrace

do_route_flush=\${1:-false}

ip link del wg-blatto || true
rm /run/wg-blatto/ || true

ip link add dev wg-blatto type wireguard
ip addr add $v4net.$id/24 dev wg-blatto metric 100
ip addr add $v6net::$id/64 dev wg-blatto metric 100
wg set wg-blatto listen-port 12061 private-key /etc/wireguard/blatto/$id.key
wg set wg-blatto peer \$(cat /etc/wireguard/blatto/blattes.pub) preshared-key /etc/wireguard/blatto/psk endpoint $blattes_ipv4:$port allowed-ips 0.0.0.0/0,::0/0
ip link set mtu 1432 dev wg-blatto
ip link set wg-blatto up

AMEN

for ups in $upstreams
do
	ups_id=upstream_${ups}_id
	ups_id=${!ups_id}
	echo ip link del wg-blatto2$ups || true
	echo ip link add wg-blatto2$ups type sit remote $ipv4_prefix.$vlid.$ups_id local any mode any
	echo ip link set wg-blatto2$ups up
	echo
done

cat <<AMEN

for ipv in 4 6
do
	for tind in 12 12{2,3,4} 612 612{2,3,4}
	do
		\$do_route_flush && ip -\$ipv route flush table \$tind
		ip -\$ipv rule add fwmark \$tind table \$tind priority \$tind
	done
	ip -\$ipv rule add fwmark 6 table 612 priority 32666
done

ip route add default via $v4net.1 dev wg-blatto table 12 metric 1100
ip route add default via $v6net::1 dev wg-blatto table 12 metric 1100

ip route add default dev wg-blatto2mn  table 122 metric 1100 src $v4net.$id
ip route add default dev wg-blatto2awn table 123 metric 1100 src $v4net.$id
ip route add default dev wg-blatto2mul table 124 metric 1100 src $v4net.$id

mkdir /run/wg-blatto/

echo $adopt > /run/wg-blatto/adopt

systemctl reload net-blatto-daemon
AMEN
if $adopt
then
cat <<AMEN
ip addr add $adopt_v4net.$id/32 dev wg-blatto metric 1000
ip addr add $adopt_v6net::$id/128 dev wg-blatto metric 1000

ip route add default dev wg-blatto table 12 metric 1000 src $adopt_v4net.$id
ip route add default dev wg-blatto table 12 metric 1000 src $adopt_v6net::$id

ip route add default dev wg-blatto2mn table 122 metric 1000 src $adopt_v4net.$id
ip route add default dev wg-blatto2awn table 123 metric 1000 src $adopt_v4net.$id
ip route add default dev wg-blatto2mul table 124 metric 1000 src $adopt_v4net.$id

ip addr del $v4net.$id/24 dev wg-blatto metric 1100
ip addr add $v4net.$id/24 dev wg-blatto metric 1100
AMEN
fi
) > /etc/net/wg-blatto

rm /etc/net/wg-blatto-route || true

chmod +x /etc/net/wg-blatto
