#!/bin/bash
CLASS=$(i3-msg -t get_tree | jq -r '.. | .nodes? | .[]? | select(.window!=null and .focused==true).window_properties.class')

echo $CLASS
if [ "$CLASS" = "Alacritty" ]; then
	(sleep 0.001; xdotool key --clearmodifiers ctrl+d;xdotool key --clearmodifiers ctrl+d )&
else
  i3-msg kill
fi
