#!/bin/bash
app="snapshoter"
version=1.5
author="Jiri Kalvoda"

if [[ "$UID" != "0" ]]
then
	root "$0" "$@"
	exit $?
fi

do_clean()
{
	if [[ "$snapdrive" != "" ]]
	then
		umount $tmpdir/fs
		rmdir $tmpdir/fs
	fi
	rmdir $tmpdir
}

err()
{
	echo -e "\e[31m\e[1m${@:2}\e[0m"
	do_clean
	exit $1
}

minus=""
while [[ "$1" == "-"* ]]
do
	minus="$minus$1"
	shift
done

device="$1"

sshcmd=""
usingSSH=false

exclude_mnt=true
exclude_aux=true
exclude_arch_cache=true
exclude_key=true
exclude_fs=true
exclude_cache=true
exclude_downloads=true
exclude_mountdir=true
excludedir_homes="'/root' '/home/*'"

snapdir="/mnt/snapshot-manual"
autosnapdir="/mnt/snapshot"

ms()
{
	ms_ret="$(movingssh -gdx $@ rsync)"
	from="$(echo "$ms_ret" | head -n1)$fromdir"
	sshcmd="$(echo "$ms_ret" | head -n2 | tail -n1)"
	usingSSH=true
}
ssh()
{
	from="$1:$fromdir"
	usingSSH=true
}

delete()
{
	for i in "$@"
	do
		echo REMOVE $i
		/usr/bin/time rm -r $i
	done
}

. ~/snapshoter.devices

if [[ "$from" == "" ]] && [[ "$device" != clean ]]
then
	echo -e "\e[31m\e[1mNo device $device\e[0m"
	exit 1
fi

[[ "$minus" == *"a"* ]] && snapdir="$autosnapdir"
[[ "$minus" == *"a"* ]] && snapdrive="$autosnapdrive"

tmpdir_template=$(basename $snapdir)-XXXXXXX

mkdir -p /mnt/snapshoter-rundir
tmpdir="$(mktemp -d -t $tmpdir_template -p /mnt/snapshoter-rundir)"
chown 700 "$tmpdir"




if [[ "$snapdrive" != "" ]]
then
	mkdir $tmpdir/fs
	mount $snapdrive $tmpdir/fs || err 100 Mount faild
	mount -o remount,rw $tmpdir/fs $tmpdir/fs || err 100 Remount faild
	snapdir=$tmpdir/fs
fi

if [[ "$device" == "clean" ]]
then
	data="$(ls $snapdir/*/working/* -d 2>/dev/null)"
	echo "$data"
	[[ "$data" == "" ]] && exit 0
	echo -e "\e[1mIF NO SNAPSHOTER RUNNING PRESS <Enter> for clean (some string to exit)\e[0m"
	read r
	if [[ "$r" != "" ]]
	then
		err 0 EXIT
	fi
	delete  $data
	do_clean
	exit 0
fi

if [[ "$minus" == *"d"* ]]
then
	data="$(ls $snapdir/$device/ok/*  -d 2>/dev/null| head -n-1 | awk 'NR % 2 == 0' )"
	echo TO DELETE:
	echo "$data"
	echo
	echo ALL FILES:
	for i in $(ls $snapdir/$device/ok/* -d)
	do
		if [[ "$data" == *"$i"* ]]
		then
			echo -e "\e[31mDELETE" "$i"
		else
			echo -e "\e[32mKEEP  " "$i"
		fi
	done

	[[ "$data" == "" ]] && exit 0
	echo -e "\e[1mPRESS <Enter> for delete this snapshots (some string to exit)\e[0m"
	read r
	if [[ "$r" != "" ]]
	then
		err 0 EXIT
	fi
	delete $data
	do_clean
	exit 0
fi

devicedir="$snapdir/$device"
okdir="$devicedir/ok"
workingdir="$devicedir/working"
date="$(date +%Y-%m-%d--%H-%M)"
mkdir -p "$okdir"
mkdir -p "$workingdir"
wto="$workingdir/$date"
okto="$okdir/$date"

linkdir="$(ls $okdir/ | tail -n1)"
[[ "$linkdir" != "" ]] && linkdir="$okdir/$linkdir"

if ! $usingSSH 
then
	echo NOT SSH
	if [[ ! -e "$from" ]]
	then
		err  101 "FROM $from NOT EXIST!"
	fi
	if [[ "$(ls $from)" == "" ]]
	then
		err 102 "FROM $from IS EMPTY!"
	fi
fi
if [[ -e "$wto" ]] || [[ -e "$okto" ]]
then
	err 100 "FILE $wto OR $okto EXIST!"
fi

to="$wto/data"
#mkdir -p "$to"

excludefile="$wto/exclude"
mkdir -p "$wto"
echo -n "" > "$excludefile"


parcmd="-atu --recursive --info=progress2 --info=name0 --delete --force --sparse --delete-excluded --stats"
unset linkcmd
[[ "$linkdir" != "" ]] && linkcmd="--link-dest=$linkdir/data/"
excludecmd="--exclude-from=$excludefile"

$exclude_fs && echo >> "$excludefile" "/dev"
$exclude_fs && echo >> "$excludefile" "/proc"
$exclude_fs && echo >> "$excludefile" "/run"
$exclude_fs && echo >> "$excludefile" "/sys"
$exclude_fs && echo >> "$excludefile" "/tmp"
$exclude_fs && echo >> "$excludefile" "/snap"
$exclude_mnt && echo >> "$excludefile" "/mnt"
$exclude_aux &&  echo >> "$excludefile" "/aux"
$exclude_arch_cache &&  echo >> "$excludefile" "/var/cache/pacman/pkg"
$exclude_arch_cache &&  echo >> "$excludefile" "/var/cache/aur/.cache"
$exclude_arch_cache &&  echo >> "$excludefile" "/var/cache/aur/.gradle"
$exclude_arch_cache &&  echo >> "$excludefile" "/var/cache/aur/.cargo"
for h_it in $excludedir_homes
do
	h="${h_it:1:-1}"
	$exclude_cache && echo >> "$excludefile" "$h/.cache"
	$exclude_key && echo >> "$excludefile" "$h/.ssh"
	$exclude_mountdir && echo >> "$excludefile" "$h/m"
	$exclude_mountdir && echo >> "$excludefile" "$h/kam"
	$exclude_downloads && echo >> "$excludefile" "$h/Downloads"
done

logcmd="--log-file=$wto/log"


echo "RUNNING SNAPSHOTER ON DEVICE $device"
echo -e  "from:    \e[1m\e[92m$from\e[0m"
[[ $sshcmd != "" ]] && echo -e  "\e[1m\e[33m$sshcmd\e[0m"
echo "to:      $okto"
echo "working: $wto"
echo "link:    $linkdir"
echo
echo "******** RSYNC ******"
echo "par:    " $parcmd
echo "link:   " $linkcmd
echo "exclude: $excludecmd"
echo -e -n "\e[33m"
cat "$excludefile"
echo -e "\e[0m"

echo rsync ${parcmd} "${linkcmd@Q}" "${excludecmd@Q}" $sshcmd "${from@Q}/" "${to@Q}/" "${logcmd@Q} " > $wto/cmd
echo -e -n "\e[96m"
cat $wto/cmd
echo -e "\e[0m"

echo "snapshot made by $app $version (c) $author on $date for device $device" > $wto/README

if [[ "$minus" != *"y"* ]]
then
	echo -e "\e[1mPRESS <Enter> for start (some string to exit)\e[0m"
	read r
	if [[ "$r" != "" ]]
	then
		rm -r $wto
		err 0 EXIT
	fi
fi

#rsync $parcmd $linkcmd "$excludecmd" "$from/" "$to/"
echo -e -n "\e[92m"
time nice -10 bash  $wto/cmd
r=$?
echo -e -n "\e[0m"

if [[ "$r" != "0" ]]
then
	echo RSYNC ERROR $r
	[[ "$r" != 24 ]] && err 1 "RSYNC ERROR"
fi
if [[ "$(ls $to)" == "" ]]
then
	err  104 "TO DIRECTORY $to IS EMPTY!"
fi
echo
echo RSYNC OK
mv $wto $okto
if [[ "$?" != "0" ]]
then
	echo 2 FINEL MV $?
fi

log_dir="$(mktemp -d)"
mkdir $log_dir/last
date -u +%s > $log_dir/last/$(cat $snapdir/name)
if [[ "$sshcmd" == "" ]]
then
	rsync  -r $log_dir/ $from/.snapshoter
else
	rsync  "${sshcmd//"'"/}" -r $log_dir/ $from/.snapshoter
fi
rm -r $log_dir


echo ALL OK
do_clean


#rsync  \
#--link-dest=/run/timeshift/backup/timeshift/snapshots/2021-03-01_19-00-08/localhost/ \
##--log-file=/run/timeshift/backup/timeshift/snapshots/2021-03-01_23-54-36/rsync-log \
#--exclude-from=/run/timeshift/backup/timeshift/snapshots/2021-03-01_23-54-36/exclude.list \
#/ /run/timeshift/backup/timeshift/snapshots/2021-03-01_23-54-36/localhost/
