#!/bin/bash

xournal()
{
	echo xournalpp "$@"
	xournalpp  "$@"
	exit $?
}

if [[ "$1" == "" ]] || [[ "$1" == -* ]]
then
	xournal "${@:1}"
elif [[ "$1" == */ ]]
then
	cd "$1"
	xournal
else
	cd "$(dirname "$1")"
	n="$(basename "$1")"
	if [[ "$n" == *.xopp ]] || [[ -f "$n" && "$n" != *.pdf ]]
	then
		xournal "$n" "${@:2}"
	fi

	[[ "$n" == *".pdf" ]] && n="${n%pdf}"
	[[ "$n" != *. ]] && n="$n."

	if [[ -f "$n"pdf && ! -f "$n"xopp ]]
	then
		xournal "$n"pdf "${@:2}"
	else
		xournal "$n"xopp "${@:2}"
	fi
fi
