#!/bin/bash
if [[ "$LD_SSHTYPE" == "" ]]
then
	export LD_SSHTYPE=localhost 
fi

if [[ "$@" == "" ]]
then
	LC_CD="$PWD" ssh root@localhost -Y -o SendEnv=LD_SSHTYPE -o SendEnv=LC_CD 
else
	LD_SSHTYPE=localhost LC_CD="$PWD" ssh root@localhost -Y -o SendEnv=LD_SSHTYPE -o SendEnv=LC_CD -t cd "$PWD" \; "$@" 
fi
