#!/bin/bash
if [[ "$LC_SSHTYPE" == "" ]]
then
	export LC_SSHTYPE=localhost 
fi

keyArg=""
[[ -e ~/.config/root_key ]] && keyArg="-i ~/.config/root_key"

if [[ "$@" == "" ]]
then
	LC_CD="$PWD" ssh root@localhost -Y -o SendEnv=LC_SSHTYPE -o SendEnv=LC_CD $keyArg
else
	LC_SSHTYPE=localhost LC_CD="$PWD" ssh root@localhost -Y -o SendEnv=LC_SSHTYPE -o SendEnv=LC_CD -t $keyArg cd "$PWD" \; "$@"
fi
