#!/bin/bash

if [[ "$name" == *"kam"* ]] || [[ "$name" == *"cam" ]] || [[ "$minus" == *"k"* ]]
then
	if [[ "$minus" != *"K"* ]]
	then
		config[ipB]=$name.kam.mff.cuni.cz
		config[portB]=22
		usernameDefault=jirikalvoda
		noDownload=1
	fi
fi
