#!/bin/bash

if [[ "$name" == *"kam"* ]] || [[ "$name" == *"cam"* ]] || [[ "$minus" == *"k"* ]]
then
	if [[ "$minus" != *"K"* ]]
	then
		if [[ "$name" == "kam" ]]
		then
			config[ipB]=kam.mff.cuni.cz
		else
			config[ipB]=$name.kam.mff.cuni.cz
		fi
		config[portB]=22
		usernameDefault=jirikalvoda
		noDownload=1
	fi
fi
